### ISSUE TITLE
腾讯云轻量重装fedora cloudInit报错导致无法完成重装

### ISSUE THREAD

**Issue by Womsxd** [bin456789/reinstall#246]
原来的系统：CentOS Stream 8
要安装的系统：fedora41
遇到的问题：截图或者登录 SSH 获取日志 /reinstall.log

vnc:

![Image](https://github.com/user-attachments/assets/f27041eb-0d61-4ce0-9da4-63d2eca11cdf)

ssh:

![Image](https://github.com/user-attachments/assets/79e3f609-9dd3-4475-8e91-ac88a5e87238)

Original system:
System to be installed:
Issues encountered: Screenshot or log in via SSH to get the logs from /reinstall.log

**Comment by bin456789** [comment]
请发下 /net.cfg 的内容

**Comment by Womsxd** [comment]
```
localhost:/# cat net.cfg 
network:
  version: 1
  config:
    - type: physical
      name: eth0
      mac_address: 52:54:00:09:15:71
      subnets:
        - type: dhcp4
```
